"""empty message

Revision ID: 067be5e0157f
Revises: e0e741e6d389
Create Date: 2025-03-19 16:32:46.821447

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '067be5e0157f'
down_revision = 'e0e741e6d389'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('homework_statistic', schema=None) as batch_op:
        batch_op.drop_column('college')
        batch_op.drop_column('class_name')
        batch_op.drop_column('school')
        batch_op.drop_column('major')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('homework_statistic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('major', mysql.VARCHAR(length=80), nullable=True))
        batch_op.add_column(sa.Column('school', mysql.VARCHAR(length=80), nullable=True))
        batch_op.add_column(sa.Column('class_name', mysql.VARCHAR(length=80), nullable=True))
        batch_op.add_column(sa.Column('college', mysql.VARCHAR(length=80), nullable=True))

    # ### end Alembic commands ###
