"""empty message

Revision ID: 4dcc26af386a
Revises: d2c83409de8a
Create Date: 2025-03-19 15:48:49.787961

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4dcc26af386a'
down_revision = 'd2c83409de8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('homework_statistic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score9', sa.Float(), nullable=True))
        batch_op.alter_column('score1',
               existing_type=mysql.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('score2',
               existing_type=mysql.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('score3',
               existing_type=mysql.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('score4',
               existing_type=mysql.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('score5',
               existing_type=mysql.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('score6',
               existing_type=mysql.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('score7',
               existing_type=mysql.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('score8',
               existing_type=mysql.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.drop_column('submit_time8')
        batch_op.drop_column('submit_time1')
        batch_op.drop_column('submit_time7')
        batch_op.drop_column('submit_time6')
        batch_op.drop_column('submit_time5')
        batch_op.drop_column('submit_time2')
        batch_op.drop_column('submit_time4')
        batch_op.drop_column('submit_time3')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('homework_statistic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submit_time3', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('submit_time4', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('submit_time2', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('submit_time5', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('submit_time6', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('submit_time7', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('submit_time1', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('submit_time8', mysql.VARCHAR(length=50), nullable=True))
        batch_op.alter_column('score8',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('score7',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('score6',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('score5',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('score4',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('score3',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('score2',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('score1',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(),
               existing_nullable=True)
        batch_op.drop_column('score9')

    # ### end Alembic commands ###
