"""empty message

Revision ID: 5a4fa81b92a6
Revises: 850d14a51522
Create Date: 2025-03-18 09:45:01.956413

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5a4fa81b92a6'
down_revision = '850d14a51522'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('homework_statistics')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('homework_statistics',
    sa.Column('id', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('score1', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('submit_time1', mysql.DATETIME(), nullable=True),
    sa.Column('score2', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('submit_time2', mysql.DATETIME(), nullable=True),
    sa.Column('score3', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('submit_time3', mysql.DATETIME(), nullable=True),
    sa.Column('score4', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('submit_time4', mysql.DATETIME(), nullable=True),
    sa.Column('score5', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('submit_time5', mysql.DATETIME(), nullable=True),
    sa.Column('score6', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('submit_time6', mysql.DATETIME(), nullable=True),
    sa.Column('score7', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('submit_time7', mysql.DATETIME(), nullable=True),
    sa.Column('score8', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('submit_time8', mysql.DATETIME(), nullable=True),
    sa.Column('school', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('college', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('major', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('class_name', mysql.VARCHAR(length=80), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], name='homework_statistics_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
