"""empty message

Revision ID: 804a032e670d
Revises: 067be5e0157f
Create Date: 2025-03-30 21:05:23.918004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '804a032e670d'
down_revision = '067be5e0157f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
