"""添加作业统计表

Revision ID: 850d14a51522
Revises: b650d471895b
Create Date: 2025-03-18 08:58:26.470974

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '850d14a51522'
down_revision = 'b650d471895b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('homework_statistic')
    with op.batch_alter_table('homework_statistics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class_name', sa.String(length=80), nullable=True))
        batch_op.alter_column('school',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=80),
               existing_nullable=True)
        batch_op.alter_column('college',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=80),
               existing_nullable=True)
        batch_op.alter_column('major',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=80),
               existing_nullable=True)
        batch_op.alter_column('score1',
               existing_type=mysql.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('score2',
               existing_type=mysql.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('score3',
               existing_type=mysql.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('score4',
               existing_type=mysql.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('score5',
               existing_type=mysql.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('score6',
               existing_type=mysql.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('score7',
               existing_type=mysql.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('score8',
               existing_type=mysql.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.drop_column('class')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('homework_statistics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class', mysql.VARCHAR(length=50), nullable=True))
        batch_op.alter_column('score8',
               existing_type=sa.Integer(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('score7',
               existing_type=sa.Integer(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('score6',
               existing_type=sa.Integer(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('score5',
               existing_type=sa.Integer(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('score4',
               existing_type=sa.Integer(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('score3',
               existing_type=sa.Integer(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('score2',
               existing_type=sa.Integer(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('score1',
               existing_type=sa.Integer(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('major',
               existing_type=sa.String(length=80),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('college',
               existing_type=sa.String(length=80),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('school',
               existing_type=sa.String(length=80),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.drop_column('class_name')

    op.create_table('homework_statistic',
    sa.Column('id', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('score1', mysql.FLOAT(), nullable=True),
    sa.Column('submit_time1', mysql.DATETIME(), nullable=True),
    sa.Column('score2', mysql.FLOAT(), nullable=True),
    sa.Column('submit_time2', mysql.DATETIME(), nullable=True),
    sa.Column('score3', mysql.FLOAT(), nullable=True),
    sa.Column('submit_time3', mysql.DATETIME(), nullable=True),
    sa.Column('score4', mysql.FLOAT(), nullable=True),
    sa.Column('submit_time4', mysql.DATETIME(), nullable=True),
    sa.Column('score5', mysql.FLOAT(), nullable=True),
    sa.Column('submit_time5', mysql.DATETIME(), nullable=True),
    sa.Column('score6', mysql.FLOAT(), nullable=True),
    sa.Column('submit_time6', mysql.DATETIME(), nullable=True),
    sa.Column('score7', mysql.FLOAT(), nullable=True),
    sa.Column('submit_time7', mysql.DATETIME(), nullable=True),
    sa.Column('score8', mysql.FLOAT(), nullable=True),
    sa.Column('submit_time8', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], name='homework_statistic_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
