"""更新用户模型

Revision ID: b650d471895b
Revises: 
Create Date: 2025-03-17 10:25:26.460992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b650d471895b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('homework_statistics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('college', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('major', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('class', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('homework_statistics', schema=None) as batch_op:
        batch_op.drop_column('class')
        batch_op.drop_column('major')
        batch_op.drop_column('college')
        batch_op.drop_column('school')

    # ### end Alembic commands ###
